"""
Django settings for labqc project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev key locally; set a real DJANGO_SECRET_KEY
# environment variable in the Vercel project settings for the live demo.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-tkrw&8g+3qd&3fh7px9rc2$(kd+b2^t##crgg@tyccw69-^y97',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in the Vercel project's environment variables.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Vercel's preview/production URLs, plus any host supplied via env var
# (comma-separated), e.g. DJANGO_ALLOWED_HOSTS=labqc.vercel.app
ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost']
_extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]
# Vercel also sets VERCEL_URL to the current deployment's hostname
if os.environ.get('VERCEL_URL'):
    ALLOWED_HOSTS.append(os.environ['VERCEL_URL'])
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if '.' in h]


# Application definition

INSTALLED_APPS = [
    'qc',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labqc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'qc.context_processors.notifications',
                'qc.context_processors.nav_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'labqc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# IMPORTANT — read before deploying to Vercel:
# Vercel's serverless functions have a read-only filesystem (except /tmp,
# which is wiped between invocations), so the bundled SQLite file cannot
# reliably store new data once deployed — writes may vanish between
# requests. For a live client demo this is fine for read-only browsing of
# the seeded dataset, but registering/testing new samples through the
# deployed site will not persist. Set a DATABASE_URL environment variable
# (e.g. from Vercel Postgres, Neon, or Supabase) in the Vercel project
# settings to use a real persistent database instead; falls back to the
# local SQLite file when DATABASE_URL is not set.
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL', conn_max_age=600, ssl_require=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Plain (non-manifest) compressed storage: WhiteNoise serves straight from
# STATIC_ROOT, so a missed `collectstatic` degrades to a 404 on the JS file
# rather than a 500 on every page (which is what the hashed/manifest storage
# would do if the manifest is missing).
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# (Not used by the app yet — no view sends email — but set correctly in case
# password-reset or notification email is added later. Note: the previous
# `MAILERS` key here was not a real Django setting, so it was silently doing
# nothing; EMAIL_BACKEND is the setting Django actually reads.)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type for models that don't specify one.
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
