# Generated by Django 6.1 on 2026-08-30 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lab_technician', 'Lab Technician'), ('site_engineer', 'Site Engineer'), ('project_manager', 'Project Manager')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('batch_no', models.CharField(max_length=20)),
                ('mixer_id', models.CharField(max_length=20)),
                ('casting_date', models.DateField()),
                ('concrete_grade', models.CharField(choices=[('Grade 20', 'Grade 20'), ('Grade 25', 'Grade 25'), ('Grade 30', 'Grade 30'), ('Grade 35', 'Grade 35')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlumpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('slump_mm', models.PositiveIntegerField()),
                ('witnessed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slump_test', to='qc.sample')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slump_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuringStrengthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curing_age_days', models.PositiveSmallIntegerField(choices=[(7, '7 days'), (14, '14 days'), (21, '21 days'), (28, '28 days')])),
                ('test_date', models.DateField()),
                ('load_kn', models.DecimalField(decimal_places=2, help_text='Failure load in kN', max_digits=8)),
                ('cross_sectional_area_mm2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strength_tests', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_tests', to='qc.sample')),
            ],
            options={
                'ordering': ['sample__sample_id', 'curing_age_days'],
                'unique_together': {('sample', 'curing_age_days')},
            },
        ),
    ]
